[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_tts"
version = "1.0.0"
description = "Local only TTS"
requires-python = ">=3.7"
dependencies = ["TTS", "torch", "asyncio", "nanoid", "termcolor"]

